<?php

namespace App\Notifications;

use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\HtmlString;

class CustomRegistrationConfirmNotification extends Notification
{
    /**
     * The callback that should be used to build the mail message.
     *
     * @var \Closure|null
     */
    public static $toMailCallback;

    /**
     * Get the notification's channels.
     *
     * @param mixed $notifiable
     * @return array|string
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Build the mail representation of the notification.
     *
     * @param mixed $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->subject(Lang::get('Verify Email Address'))
            ->line(Lang::get('You\'ve registered'))
            ->line(Lang::get('Please use the pin code to verify your e-mail address.'))
            ->line(new HtmlString('<h4>' . Lang::get('PIN:') . ' ' . $notifiable->email_verify_pin . '</h4>'))
            ->line(Lang::get('If you did not create an account, no further action is required.'))
            ->line(new HtmlString('<small>' . Lang::get('This is an autogenerated mail, so please don\'t reply') . '<a href="mailto:webmaster@pannon-viz.hu">webmaster@pannon-viz.hu</a></small>'));
    }

    /**
     * Set a callback that should be used when building the notification mail message.
     *
     * @param \Closure $callback
     * @return void
     */
    public static function toMailUsing($callback)
    {
        static::$toMailCallback = $callback;
    }
}
